import Foundation

/// Chinese labels for values controlled by the service. Free-form content is
/// deliberately returned unchanged because it was entered by a user/admin.
func adminSystemLabel(_ value: String) -> String {
    let labels: [String: String] = [
        "narrow_body": "窄体客机",
        "wide_body": "宽体客机",
        "regional": "支线客机",
        "cargo": "货机",
        "business_jet": "公务机",
        "general": "通用航空器",
        "helicopter": "直升机",
        "military": "军用航空器",
        "other": "其他",
        "airport": "机场",
        "spotting_point": "拍摄点",
        "emu": "动车组",
        "locomotive": "机车",
        "passenger_car": "客车",
        "freight": "货运",
        "metro": "地铁",
        "tram": "有轨电车",
        "high_speed": "高速铁路",
        "intercity": "城际铁路",
        "conventional": "普速铁路",
        "active": "正常",
        "inactive": "停用",
        "pending": "待处理",
        "approved": "已通过",
        "rejected": "已驳回",
        "open": "开放",
        "closed": "已关闭",
        "cancelled": "已取消",
        "draft": "草稿",
        "published": "已发布",
        "archived": "已归档",
        "suspended": "暂停",
        "new": "新反馈",
        "read": "已读",
        "replied": "已回复",
        "queued": "排队中",
        "sent": "已发送",
        "failed": "失败",
        "received": "已接收",
        "processed": "已处理",
        "ignored": "已忽略",
        "visible": "正常显示",
        "hidden": "已隐藏",
        "deleted": "已删除",
        "public": "公开",
        "unlisted": "不公开列出",
        "private": "私密",
        "event": "事件",
        "location": "地点",
        "aircraft": "航空器",
        "railway": "铁路",
        "livery": "涂装",
        "special": "特殊",
        "first": "初审",
        "second": "复核",
        "jury": "评审团",
        "appeal": "申诉",
        "conflict": "冲突仲裁",
        "approve": "通过",
        "reject": "驳回",
        "escalate": "转交复核",
    ]
    return labels[value] ?? value
}

/// Human-readable label for dotted server identifiers used by audit logs.
func adminCompositeSystemLabel(_ value: String) -> String {
    let parts: [String: String] = [
        "admin": "后台", "user": "用户", "photo": "图片", "content": "内容",
        "comment": "评论", "collection": "收藏集", "tag": "标签", "group": "小组",
        "type": "类型", "history": "历史", "activity": "活动",
        "post": "帖子", "report": "举报", "appeal": "申诉", "review": "审核",
        "reason": "驳回理由", "ticket": "工单", "feedback": "反馈", "correction": "纠错",
        "license": "授权", "priority": "优先额度", "application": "申请", "reference": "字典",
        "operator": "运营人", "aircraft_event": "飞机事件", "forecast": "预报", "cache": "缓存",
        "announcement": "公告", "news": "资讯", "ranking": "赛事", "claim": "认领 / 领奖",
        "entry": "参赛作品", "participant": "参与者", "vote": "投票", "jury": "评审团",
        "badge": "徽章", "risk": "风控", "keyword": "关键词", "ip": "网络地址",
        "rbac": "权限", "role": "用户组", "team": "团队", "partner": "合作商",
        "settings": "设置", "watermark": "水印", "warning": "违规", "quota": "配额",
        "api": "接口", "apikey": "接口密钥", "email": "邮件", "session": "会话",
        "create": "新建", "add": "添加", "update": "更新", "edit": "编辑",
        "delete": "删除", "remove": "移除", "rename": "重命名", "merge": "合并",
        "approve": "通过", "reject": "驳回", "cancel": "取消", "close": "关闭",
        "publish": "发布", "export": "导出", "import": "导入", "backfill": "回填",
        "assign": "分配", "appoint": "任命", "transfer": "转移", "dissolve": "解散",
        "ban": "封禁", "unban": "解除封禁", "mute": "禁言", "unmute": "解除禁言",
        "suspend": "暂停", "unsuspend": "解除暂停", "grant": "授予", "revoke": "撤销",
        "reset": "重置", "toggle": "切换", "status": "更改状态", "config": "配置",
        "requirements": "报名要求", "reorder": "调整顺序", "reply": "回复",
        "takeover": "接管", "flush": "清空", "reconnect": "重连",
        "rescan": "重新扫描", "run": "立即运行", "view": "查看", "manage": "管理",
    ]
    let labels = value.replacingOccurrences(of: "_", with: ".")
        .split(separator: ".")
        .compactMap { parts[String($0)] }
    return labels.isEmpty ? "后台操作" : labels.joined(separator: " · ")
}
